DEFAULT_PRESET_KEY = "classic_audio"
DEFAULT_MODE_TITLE = "Game Mode Details"

DEFAULT_BONUS_POINTS_BOTH = 1
DEFAULT_WRONG_GUESS_PENALTY = 0
DEFAULT_REQUIRED_POINTS_TO_WIN = 15

ROUND_TYPE_PHONE_REQUIREMENTS: dict[str, bool] = {
    "audio": False,
    "video": False,
    "lyrics": True,
}

DEFAULT_PLAYBACK_PROVIDER = "local_files"
DEFAULT_TRACK_DURATION_SECONDS = 240
DEFAULT_SNIPPET_START_OFFSETS = "0,0,0"